#!/usr/bin/env sh

set -e

caddy=/usr/bin/caddy
chown root:wheel ${caddy}
ldid -S ${caddy}

config=/usr/etc/caddy/Caddyfile
if [ -f ${config}.bak ]; then
  mv ${config}.bak ${config}
fi

log=/var/log/caddy
if [ ! -d ${log} ]; then
  mkdir -p ${log}
fi

daemon=/Library/LaunchDaemons/com.github.caddyserver.caddy.plist
chown root:wheel ${daemon}
launchctl load -w ${daemon}